### ISSUE TITLE
大佬 求有云服务器青龙2.8+Ninja面板配置教 

### ISSUE THREAD

**Issue by Dante-LI** [abctel/abctel.github.io#4]

**Comment by abctel** [comment]
有云服务器？？这个我没接触过，你的意思是云服务器吗？

**Comment by Dante-LI** [comment]
CentOS7    Linux  青龙2.8+Ninja面板配置教

**Comment by Dante-LI** [comment]
CentOS7 Linux 青龙2.8+Ninja面板配置教程

**Comment by abctel** [comment]
@Dante-LI 我不太确定青龙有自部署的代码？你那里有吗？如果有你可以告诉我个链接，我测试一下。

**Comment by Dante-LI** [comment]
https://www.notion.so/1c598629675145988b43a37998a1604a  這個鏈接裡面的教程太複雜沒看懂

**Comment by abctel** [comment]
@Dante-LI 明白了，这个教程就是使用Docker进行安装。我Blog上的安装教程只是少了Docker安装步骤，这方面你只需根据链接里面的 https://blog.csdn.net/weixin_42565036/article/details/117569495 一步步操作即可，在启动成功青龙面板之后根据我提供的教程安装Ninja的步骤完成安装即可。

**Comment by Dante-LI** [comment]
我是先安装了

> @但丁-LI明白了，这个教程就是使用泊坞窗进行安装。我博客上的安装教程只是少了泊坞窗安装步骤，方面这你只需根据链接里面的[https://blog.csdn.net/weixin_42565036/article /details/117569495](https://blog.csdn.net/weixin_42565036/article/details/117569495)一步步操作完成后，在启动成功青龙面板根据我提供的教程安装忍者的步骤安装完成。

我是先安装了docker和相关依赖，在安照你的操作流程，无法启动青龙面板

**Comment by abctel** [comment]
> 我是先安装了
> 
> > @但丁-LI明白了，这个教程就是使用泊坞窗进行安装。我博客上的安装教程只是少了泊坞窗安装步骤，方面这你只需根据链接里面的[https://blog.csdn.net/weixin_42565036/article /details/117569495](https://blog.csdn.net/weixin_42565036/article/details/117569495)一步步操作完成后，在启动成功青龙面板根据我提供的教程安装忍者的步骤安装完成。
> 
> 我是先安装了docker和相关依赖，在安照你的操作流程，无法启动青龙面板

你可以有两个咨询方式：
方式一、提供你的有云服务器，我安装测试后制作一篇教程。
方式二、提供你的出错代码或者出错截图，方便我发现问题。

**Comment by Dante-LI** [comment]
> > 我是先安装了
> > > @但丁-LI明白了，这个教程就是使用泊坞窗进行安装。我博客上的安装教程只是少了泊坞窗安装步骤，方面这你只需根据链接里面的[https://blog.csdn.net/weixin_42565036/article /details/117569495](https://blog.csdn.net/weixin_42565036/article/details/117569495)一步步操作完成后，在启动成功青龙面板根据我提供的教程安装忍者的步骤安装完成。
> > 
> > 
> > 我是先安装了docker和相关依赖，在安照你的操作流程，无法启动青龙面板
> 
> 你可以有两个咨询方式：
> 方式一、提供你的有云服务器，我安装测试后制作一篇教程。
> 方式二、提供你的出错代码或者出错截图，方便我发现问题。

怎麼聯繫您  我提供云服務器

**Comment by abctel** [comment]
> > > 我是先安装了
> > > > @但丁-LI明白了，这个教程就是使用泊坞窗进行安装。我博客上的安装教程只是少了泊坞窗安装步骤，方面这你只需根据链接里面的[https://blog.csdn.net/weixin_42565036/article /details/117569495](https://blog.csdn.net/weixin_42565036/article/details/117569495)一步步操作完成后，在启动成功青龙面板根据我提供的教程安装忍者的步骤安装完成。
> > > 
> > > 
> > > 我是先安装了docker和相关依赖，在安照你的操作流程，无法启动青龙面板
> > 
> > 
> > 你可以有两个咨询方式：
> > 方式一、提供你的有云服务器，我安装测试后制作一篇教程。
> > 方式二、提供你的出错代码或者出错截图，方便我发现问题。
> 
> 怎麼聯繫您 我提供云服務器

看你使用的是繁体字，可能不会使用QQ，你可以Email到abctel@gmail.com或者abctel@qq.com告诉我你的云服务器。也可以告诉你我你其它的联系方式，例如：QQ，wechat，TG。
